### ISSUE TITLE
Game Crash when launching Geode

### ISSUE THREAD

**Issue by DroguitoP** [undefined06855/EditorMusic#11]
After having placed the songs in the folder in the mod files, when you restart Geode to load the songs, when the mod starts loading, the game crashes, making it impossible to start Geode.
I tried with just one song, several songs, having only the "Editor Music" mod activated to avoid incompatibility with other mods and the problem still occurs.
I don't know if I did something wrong but it's really annoying.

**Comment by undefined06855** [comment]
can you send the logs and the crash log?

**Comment by DroguitoP** [comment]
Here it is
[Crash 2024-05-09 20.36.27.dmp](https://github.com/undefined06855/EditorMusic/files/15274024/Crash.2024-05-09.20.36.27.dmp)

**Comment by undefined06855** [comment]
can you send the normal logs as well?

**Comment by undefined06855** [comment]
can you send the normal logs as well?

edit: That crash is also a Death markers crash and not EditorMusic

**Comment by DroguitoP** [comment]
[Geode 2024-05-10 12.34.09.log](https://github.com/undefined06855/EditorMusic/files/15278734/Geode.2024-05-10.12.34.09.log)

**Comment by DroguitoP** [comment]
I deleted all the mods I had downloaded (I only left Node IDs and Editor Music installed) and it still crashes.

**Comment by undefined06855** [comment]
could you send the crashlog called "Crash 2024-05-10 12.34.09.dmp"

**Comment by DroguitoP** [comment]
[Geode 2024-05-10 12.34.09.log](https://github.com/undefined06855/EditorMusic/files/15281351/Geode.2024-05-10.12.34.09.log)
