### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by AlaskaFX** [undefined06855/EditorMusic#12]
This mod is great, and I'm glad it exists. However, there are some issues that need addressing.

1. Duration of the music is not displayed accurately, and this is the case with all songs. The music ends and then there is just silence.
![GeometryDash_Boosr7kA8m](https://github.com/undefined06855/EditorMusic/assets/169469693/71e243ea-b34f-46aa-8fae-09a29c10231d)

2. Mod crashes at the start of the game, and as far as I can tell, this is due to a large RAM load. You can compare it yourself.
Disabled:
![Taskmgr_PklaRPFyhD](https://github.com/undefined06855/EditorMusic/assets/169469693/696e8908-8e48-4047-81ab-f97e1958e1f9)
Enabled (55 songs, total size 100 MB - If I start uploading more songs, crashing will be 100%):
![Taskmgr_VHjlFSPBEd](https://github.com/undefined06855/EditorMusic/assets/169469693/3e0ccce5-b8cd-4bb7-ada9-05f51fe00362)

Here's logs, I was trying to start the game here when I uploaded 100 songs to a folder with a total size of 250 MB -> 
[Geode 2024-05-08 18.35.55.log](https://github.com/undefined06855/EditorMusic/files/15276590/Geode.2024-05-08.18.35.55.log)

**Comment by undefined06855** [comment]
#1 is  a known bug, I'll fix that soon
for #2, you can install the 4GB patch (misc bugfixes mod includes that for you) or just use less / lower quality songs - eventually I'll implement only loading songs when needed

**Comment by undefined06855** [comment]
fixed in v1.3.6 since songs now load only when they're needed
