### ISSUE TITLE
Not sure if that's your bug but I'll still say it

### ISSUE THREAD

**Issue by im-blad** [undefined06855/EditorMusic#13]
Something weird occured when I was making a level
If you play, and stop at the exact same moment as the song starts playing, the song won't stop playing

https://github.com/undefined06855/EditorMusic/assets/148497646/f55cce32-0bdc-4b2a-9a05-0a2676c7c259

(Yes, the mod is enabled)
(Yes, the song trigger is attached to a spawn trigger, not sure if that's required for the bug to happen)
(it also plays together with the song played in the editor from a mod)

**Comment by undefined06855** [comment]
im 99% sure this is not my issue, and even if it is there's definitely not enough information in that recording to figure out what's causing it so in the meantime i'll just close this
