### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by nbieberitz** [undefined06855/EditorMusic#14]
On Android, do I need a specific app in order to open the file needed to add the music? I can't figure out how to open the file.

**Comment by undefined06855** [comment]
what? just use your normal files app to open the folder

**Comment by nbieberitz** [comment]
It doesn't allow me for some reason...

**Comment by undefined06855** [comment]
this isn't really my issue, but what phone do you have?

**Comment by nbieberitz** [comment]
What do you mean?
