### ISSUE TITLE
2 Issues in a row.

### ISSUE THREAD

**Issue by NonCloud9** [undefined06855/EditorMusic#16]
Back again with 2 new bugs.

The first one is the Song name on the current song menu doesn't show properly.

https://github.com/undefined06855/EditorMusic/assets/85463024/67999e01-b5b4-48c6-ad85-2394faeeba4b

And the other (which i didn't take footage) is after updating the mod i went to test it out on the editor and after loading the game just crash, i have already music on the mod's folder 11 mp3s, 1 WAV and 1 OGG and after testing if i take the OGG file the mod will work without problems but more strange is when i putted the OGG file back to the mod's folder, the game wont crash again after being responsable for crashing.

https://github.com/undefined06855/EditorMusic/assets/85463024/91c35897-fbaf-4b26-8603-31276be62be9

Here's the crashlogs:
[2024-06-28_20-40-43.txt](https://github.com/user-attachments/files/16038443/2024-06-28_20-40-43.txt)
[2024-06-28_20-41-54.txt](https://github.com/user-attachments/files/16038444/2024-06-28_20-41-54.txt)
[2024-06-28_20-43-03.txt](https://github.com/user-attachments/files/16038445/2024-06-28_20-43-03.txt)
[2024-06-28_20-46-20.txt](https://github.com/user-attachments/files/16038446/2024-06-28_20-46-20.txt)

**Comment by undefined06855** [comment]
Could you send the songs and the normal logs when the game crashed?

**Comment by NonCloud9** [comment]
[Geode 2024-06-28 20.43.31.log](https://github.com/user-attachments/files/16040798/Geode.2024-06-28.20.43.31.log)
[Geode 2024-06-28 20.43.56.log](https://github.com/user-attachments/files/16040799/Geode.2024-06-28.20.43.56.log)
[Geode 2024-06-28 20.45.48.log](https://github.com/user-attachments/files/16040802/Geode.2024-06-28.20.45.48.log)
[Geode 2024-06-28 20.46.37.log](https://github.com/user-attachments/files/16040803/Geode.2024-06-28.20.46.37.log)
[Geode 2024-06-28 20.33.56.log](https://github.com/user-attachments/files/16040804/Geode.2024-06-28.20.33.56.log)
[Geode 2024-06-28 20.35.19.log](https://github.com/user-attachments/files/16040805/Geode.2024-06-28.20.35.19.log)
[Geode 2024-06-28 20.38.27.log](https://github.com/user-attachments/files/16040806/Geode.2024-06-28.20.38.27.log)
[Geode 2024-06-28 20.41.22.log](https://github.com/user-attachments/files/16040807/Geode.2024-06-28.20.41.22.log)
[Geode 2024-06-28 20.42.06.log](https://github.com/user-attachments/files/16040808/Geode.2024-06-28.20.42.06.log)
[Geode 2024-06-28 20.42.32.log](https://github.com/user-attachments/files/16040809/Geode.2024-06-28.20.42.32.log)


https://drive.google.com/drive/folders/1fSY8u-dV1tmXWyN-wm0SDE8Qe3qNOGLz?usp=sharing

**Comment by undefined06855** [comment]
alright I'll look at these tonight

**Comment by undefined06855** [comment]
ok the issue with the crashes has been fixed - Crash Creator.mp3 had a song name that wasn't a string for whatever reason

**Comment by undefined06855** [comment]
in fact, I think that's why the other issue was happening as well - i believe these have both been fixed now in v1.3.7

**Comment by NonCloud9** [comment]
It's now fixed thanks.

Also is funny that the same song i used for the song reproducer mockup was responsible for the bug, maybe that string was created when i copied the song title from youtube to paste it quickly on the file.
