### ISSUE TITLE
Mod won't recognize songs in folder

### ISSUE THREAD

**Issue by TheNormalestPeep** [undefined06855/EditorMusic#17]
![image](https://github.com/undefined06855/EditorMusic/assets/75856557/b75a0f2e-735a-4c2f-8204-663ccd9d8b8c)

**Comment by TheNormalestPeep** [comment]
issue was that "open folder" opens %localappdata% instead of the proper folder :(

**Comment by Daviniccius** [comment]
> issue was that "open folder" opens %localappdata% instead of the proper folder :(

what is the proper folder?
