### ISSUE TITLE
Unknown character at beginning of song title, does not exist in file explorer

### ISSUE THREAD

**Issue by Octostomp** [undefined06855/EditorMusic#18]
When I view the song title of my audio, there is an unknown character at the beginning of the name.
![Screenshot 2024-07-07 103752](https://github.com/undefined06855/EditorMusic/assets/173054260/52c491a3-18bb-45ad-aef0-20128bba9470)
But in file explorer, when I view the MP3 title, there's nothing.
![Screenshot 2024-07-07 103837](https://github.com/undefined06855/EditorMusic/assets/173054260/0154cd9b-a33a-408a-8f6b-e0547a62a1b6)
Why is this happening? I can provide any info you need.

**Comment by undefined06855** [comment]
That's the [byte order mark](https://en.m.wikipedia.org/wiki/Byte_order_mark), I still need to remove it but in the meantime you can change the unknown character in the settings to appear as a blank space to make it invisible
