### ISSUE TITLE
Crash when click pause on editor

### ISSUE THREAD

**Issue by RuslanGMD** [undefined06855/EditorMusic#24]

**Comment by undefined06855** [comment]
this was fixed in the latest version

**Comment by undefined06855** [comment]
ok so basically this wasnt fixed in the latest version i lied

**Comment by undefined06855** [comment]
ok i fixed this maybe potentially i hope so anyway

**Comment by RuslanGMD** [comment]
> ok i fixed this maybe potentially i hope so anyway

Yes, game not crash if click pause on editor
