### ISSUE TITLE
strange sounds when clicking in the editor

### ISSUE THREAD

**Issue by RuslanGMD** [undefined06855/EditorMusic#25]

**Comment by RuslanGMD** [comment]
https://github.com/user-attachments/assets/39ef0e43-9e26-4dd4-809a-231cf1b7ef4b

**Comment by undefined06855** [comment]
what mods do you have installed this is not editormusic

**Comment by RuslanGMD** [comment]
> what mods do you have installed this is not editormusic 
this is due to setting "Show touch" in QOLMod

**Comment by RuslanGMD** [comment]
this is due to setting "Show touches" in QOLMod
