### ISSUE TITLE
Instruction unclear

### ISSUE THREAD

**Issue by Phoom02** [undefined06855/EditorMusic#3]
I put a song in directory but it doesn't play music for me. I'm on mobile and the song is mp3 file btw
![Screenshot_20240427-093616_Files](https://github.com/undefined06855/EditorMusic/assets/168250034/31d084c4-acdf-4423-af01-08f0d87efd3d)

**Comment by undefined06855** [comment]
That's the wrong folder, it should be in Geode/geode/config/undefined0.editormusic/
