### ISSUE TITLE
Music issue

### ISSUE THREAD

**Issue by im-blad** [undefined06855/EditorMusic#4]
When I try to play level music using the song button, it plays the editor song and the level song at the same time

While I stop the music using the same button, both of the songs stop

https://github.com/undefined06855/EditorMusic/assets/148497646/dc01e5a2-7169-428f-a8a8-932411f8247c

**Comment by undefined06855** [comment]
damn I kinda guessed this could be an issue, I'll look into it later today

**Comment by undefined06855** [comment]
fixed in v1.1.1
