### ISSUE TITLE
Crashing issue

### ISSUE THREAD

**Issue by Colorzize** [undefined06855/EditorMusic#5]
Ok, so this is weird.. I go into a level, select a color and crashed the game. The weirdest thing is its only for this specific level, I did test few other level but it just doesn't crash.

**Comment by undefined06855** [comment]
what

**Comment by undefined06855** [comment]
can you send the crash log and the normal logs

**Comment by Colorzize** [comment]
Sure
[Uploading logs.zip…]()

**Comment by undefined06855** [comment]
if possible could you send your `Sea Of thieves.mp3`?

**Comment by undefined06855** [comment]
this should hopefully be fixed in 1.1.2
