### ISSUE TITLE
Music menu mockup

### ISSUE THREAD

**Issue by NonCloud9** [undefined06855/EditorMusic#7]
Hey, after i enjoyed the mod i had a little mockup idea for a menu selector or viewer like this:

![EditorSong_Mockup](https://github.com/undefined06855/EditorMusic/assets/85463024/47a4089d-46d6-418b-8c9b-636c30849067)

> This menu appears when you press the song name from top.

> You can change to a previous song or next song from the list in alphabethical order.

> There's a progress bar in case you want to skip to a certain part of the song.

> The play button works if you want to resume or pause the song you're listening (Even better because i saw a bug when you reproduce a song from the song trigger, the editor's music wont pause or fade)

> The square button next to the play one restarts the music.

> The option button allows you to see the mod options.

> The note button let you see a list of the songs you have in the folder to jump to other song. (If someone puts a full playlist on the mod's folder)

> And the volume button is there if you want to tweak if the editor's song is quiet or too loud.

Hope you like this concept -NonCloud.

**Comment by undefined06855** [comment]
wait this is actually kinda good, I'll think about it

**Comment by NonCloud9** [comment]
That's nice but something i forget there is a reset button for reseting the menu if you add more songs to the folder instead of just exiting the editor, a loop and a shuffle button.

Thanks for liking it.

**Comment by undefined06855** [comment]
Added in 1.3.0

**Comment by NonCloud9** [comment]
Thank you so much.
