### ISSUE TITLE
Android external song path folder input is broken

### ISSUE THREAD

**Issue by iCraftIP** [undefined06855/EditorMusic#8]
When going into the mod's settings, when getting to the additional external path picker, there's no description of where the path is based, and the text input doesn't even allow for hyphens or slashes (either forwards and backwards) or even colons which are both necessary (I think on PC paths too) making it very much impossible to set a path to the external folder to find music to pick from on an Android device.

**Comment by undefined06855** [comment]
i cant seem to recreate it and it doesnt seem to affect anyone else so i'm just going to close it

**Comment by undefined06855** [comment]
ok so this is an issue and I didn't catch it because I had text filter bypass on in mhv8, I'll fix this either tonight or next week

**Comment by undefined06855** [comment]
fixed in 1.3.1
