### ISSUE TITLE
Android Dropped Support?

### ISSUE THREAD

**Issue by 3squ** [undefined06855/EditorMusic#9]
![Screenshot_2024-05-08-10-43-51-28_73932565f5d18c5d7f2b58eb6d5de17f](https://github.com/undefined06855/EditorMusic/assets/157225967/43b60b70-f2bf-4e29-b5d1-136ccfa1ffdc)
I can't update it to 1.2.0 because of a single mod that's unavailable to mobile, Hope it get fixed soon.

**Comment by undefined06855** [comment]
oh yeah I'll fix this rn

**Comment by undefined06855** [comment]
fixed in v1.2.1
